//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IRISA.CommunicationCenter.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WebServiceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WebServiceEntities object using the connection string found in the 'WebServiceEntities' section of the application configuration file.
        /// </summary>
        public WebServiceEntities() : base("name=WebServiceEntities", "WebServiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebServiceEntities object.
        /// </summary>
        public WebServiceEntities(string connectionString) : base(connectionString, "WebServiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebServiceEntities object.
        /// </summary>
        public WebServiceEntities(EntityConnection connection) : base(connection, "WebServiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IccClientTelegram> IccClientTelegrams
        {
            get
            {
                if ((_IccClientTelegrams == null))
                {
                    _IccClientTelegrams = base.CreateObjectSet<IccClientTelegram>("IccClientTelegrams");
                }
                return _IccClientTelegrams;
            }
        }
        private ObjectSet<IccClientTelegram> _IccClientTelegrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IccClientTelegrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIccClientTelegrams(IccClientTelegram iccClientTelegram)
        {
            base.AddObject("IccClientTelegrams", iccClientTelegram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="IccClientTelegram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IccClientTelegram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IccClientTelegram object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tELEGRAM_ID">Initial value of the TELEGRAM_ID property.</param>
        /// <param name="sOURCE">Initial value of the SOURCE property.</param>
        /// <param name="dESTINATION">Initial value of the DESTINATION property.</param>
        /// <param name="sEND_TIME">Initial value of the SEND_TIME property.</param>
        /// <param name="pROCESSED">Initial value of the PROCESSED property.</param>
        /// <param name="rEADY_FOR_CLIENT">Initial value of the READY_FOR_CLIENT property.</param>
        public static IccClientTelegram CreateIccClientTelegram(global::System.Int64 id, global::System.Int32 tELEGRAM_ID, global::System.String sOURCE, global::System.String dESTINATION, global::System.DateTime sEND_TIME, global::System.Boolean pROCESSED, global::System.Boolean rEADY_FOR_CLIENT)
        {
            IccClientTelegram iccClientTelegram = new IccClientTelegram();
            iccClientTelegram.ID = id;
            iccClientTelegram.TELEGRAM_ID = tELEGRAM_ID;
            iccClientTelegram.SOURCE = sOURCE;
            iccClientTelegram.DESTINATION = dESTINATION;
            iccClientTelegram.SEND_TIME = sEND_TIME;
            iccClientTelegram.PROCESSED = pROCESSED;
            iccClientTelegram.READY_FOR_CLIENT = rEADY_FOR_CLIENT;
            return iccClientTelegram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TELEGRAM_ID
        {
            get
            {
                return _TELEGRAM_ID;
            }
            set
            {
                OnTELEGRAM_IDChanging(value);
                ReportPropertyChanging("TELEGRAM_ID");
                _TELEGRAM_ID = StructuralObject.SetValidValue(value, "TELEGRAM_ID");
                ReportPropertyChanged("TELEGRAM_ID");
                OnTELEGRAM_IDChanged();
            }
        }
        private global::System.Int32 _TELEGRAM_ID;
        partial void OnTELEGRAM_IDChanging(global::System.Int32 value);
        partial void OnTELEGRAM_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SOURCE
        {
            get
            {
                return _SOURCE;
            }
            set
            {
                OnSOURCEChanging(value);
                ReportPropertyChanging("SOURCE");
                _SOURCE = StructuralObject.SetValidValue(value, false, "SOURCE");
                ReportPropertyChanged("SOURCE");
                OnSOURCEChanged();
            }
        }
        private global::System.String _SOURCE;
        partial void OnSOURCEChanging(global::System.String value);
        partial void OnSOURCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESTINATION
        {
            get
            {
                return _DESTINATION;
            }
            set
            {
                OnDESTINATIONChanging(value);
                ReportPropertyChanging("DESTINATION");
                _DESTINATION = StructuralObject.SetValidValue(value, false, "DESTINATION");
                ReportPropertyChanged("DESTINATION");
                OnDESTINATIONChanged();
            }
        }
        private global::System.String _DESTINATION;
        partial void OnDESTINATIONChanging(global::System.String value);
        partial void OnDESTINATIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SEND_TIME
        {
            get
            {
                return _SEND_TIME;
            }
            set
            {
                OnSEND_TIMEChanging(value);
                ReportPropertyChanging("SEND_TIME");
                _SEND_TIME = StructuralObject.SetValidValue(value, "SEND_TIME");
                ReportPropertyChanged("SEND_TIME");
                OnSEND_TIMEChanged();
            }
        }
        private global::System.DateTime _SEND_TIME;
        partial void OnSEND_TIMEChanging(global::System.DateTime value);
        partial void OnSEND_TIMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PROCESSED
        {
            get
            {
                return _PROCESSED;
            }
            set
            {
                OnPROCESSEDChanging(value);
                ReportPropertyChanging("PROCESSED");
                _PROCESSED = StructuralObject.SetValidValue(value, "PROCESSED");
                ReportPropertyChanged("PROCESSED");
                OnPROCESSEDChanged();
            }
        }
        private global::System.Boolean _PROCESSED;
        partial void OnPROCESSEDChanging(global::System.Boolean value);
        partial void OnPROCESSEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean READY_FOR_CLIENT
        {
            get
            {
                return _READY_FOR_CLIENT;
            }
            set
            {
                OnREADY_FOR_CLIENTChanging(value);
                ReportPropertyChanging("READY_FOR_CLIENT");
                _READY_FOR_CLIENT = StructuralObject.SetValidValue(value, "READY_FOR_CLIENT");
                ReportPropertyChanged("READY_FOR_CLIENT");
                OnREADY_FOR_CLIENTChanged();
            }
        }
        private global::System.Boolean _READY_FOR_CLIENT;
        partial void OnREADY_FOR_CLIENTChanging(global::System.Boolean value);
        partial void OnREADY_FOR_CLIENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BODY
        {
            get
            {
                return _BODY;
            }
            set
            {
                OnBODYChanging(value);
                ReportPropertyChanging("BODY");
                _BODY = StructuralObject.SetValidValue(value, true, "BODY");
                ReportPropertyChanged("BODY");
                OnBODYChanged();
            }
        }
        private global::System.String _BODY;
        partial void OnBODYChanging(global::System.String value);
        partial void OnBODYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TRANSFER_ID
        {
            get
            {
                return _TRANSFER_ID;
            }
            set
            {
                OnTRANSFER_IDChanging(value);
                ReportPropertyChanging("TRANSFER_ID");
                _TRANSFER_ID = StructuralObject.SetValidValue(value, "TRANSFER_ID");
                ReportPropertyChanged("TRANSFER_ID");
                OnTRANSFER_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _TRANSFER_ID;
        partial void OnTRANSFER_IDChanging(Nullable<global::System.Int64> value);
        partial void OnTRANSFER_IDChanged();

        #endregion

    }

    #endregion

}
