//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 15/02/2022 11:30:42 AM
namespace IRISA.CommunicationCenter.Adapters.Model
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for IccClientTelegrams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<IccClientTelegram> IccClientTelegrams
        {
            get
            {
                if ((this._IccClientTelegrams == null))
                {
                    this._IccClientTelegrams = base.CreateQuery<IccClientTelegram>("[IccClientTelegrams]");
                }
                return this._IccClientTelegrams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<IccClientTelegram> _IccClientTelegrams;
        /// <summary>
        /// There are no comments for IccClientTelegrams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToIccClientTelegrams(IccClientTelegram iccClientTelegram)
        {
            base.AddObject("IccClientTelegrams", iccClientTelegram);
        }
    }
    /// <summary>
    /// There are no comments for Model.IccClientTelegram in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Model", Name="IccClientTelegram")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class IccClientTelegram : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new IccClientTelegram object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="tELEGRAM_ID">Initial value of TELEGRAM_ID.</param>
        /// <param name="sOURCE">Initial value of SOURCE.</param>
        /// <param name="dESTINATION">Initial value of DESTINATION.</param>
        /// <param name="sEND_TIME">Initial value of SEND_TIME.</param>
        /// <param name="pROCESSED">Initial value of PROCESSED.</param>
        /// <param name="rEADY_FOR_CLIENT">Initial value of READY_FOR_CLIENT.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static IccClientTelegram CreateIccClientTelegram(long id, int tELEGRAM_ID, string sOURCE, string dESTINATION, global::System.DateTime sEND_TIME, bool pROCESSED, bool rEADY_FOR_CLIENT)
        {
            IccClientTelegram iccClientTelegram = new IccClientTelegram();
            iccClientTelegram.ID = id;
            iccClientTelegram.TELEGRAM_ID = tELEGRAM_ID;
            iccClientTelegram.SOURCE = sOURCE;
            iccClientTelegram.DESTINATION = dESTINATION;
            iccClientTelegram.SEND_TIME = sEND_TIME;
            iccClientTelegram.PROCESSED = pROCESSED;
            iccClientTelegram.READY_FOR_CLIENT = rEADY_FOR_CLIENT;
            return iccClientTelegram;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property TELEGRAM_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TELEGRAM_ID
        {
            get
            {
                return this._TELEGRAM_ID;
            }
            set
            {
                this.OnTELEGRAM_IDChanging(value);
                this.ReportPropertyChanging("TELEGRAM_ID");
                this._TELEGRAM_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TELEGRAM_ID");
                this.OnTELEGRAM_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TELEGRAM_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTELEGRAM_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTELEGRAM_IDChanged();
        /// <summary>
        /// There are no comments for property SOURCE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string SOURCE
        {
            get
            {
                return this._SOURCE;
            }
            set
            {
                this.OnSOURCEChanging(value);
                this.ReportPropertyChanging("SOURCE");
                this._SOURCE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SOURCE");
                this.OnSOURCEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _SOURCE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSOURCEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSOURCEChanged();
        /// <summary>
        /// There are no comments for property DESTINATION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DESTINATION
        {
            get
            {
                return this._DESTINATION;
            }
            set
            {
                this.OnDESTINATIONChanging(value);
                this.ReportPropertyChanging("DESTINATION");
                this._DESTINATION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DESTINATION");
                this.OnDESTINATIONChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DESTINATION;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESTINATIONChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESTINATIONChanged();
        /// <summary>
        /// There are no comments for property SEND_TIME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime SEND_TIME
        {
            get
            {
                return this._SEND_TIME;
            }
            set
            {
                this.OnSEND_TIMEChanging(value);
                this.ReportPropertyChanging("SEND_TIME");
                this._SEND_TIME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SEND_TIME");
                this.OnSEND_TIMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _SEND_TIME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSEND_TIMEChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSEND_TIMEChanged();
        /// <summary>
        /// There are no comments for property PROCESSED in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool PROCESSED
        {
            get
            {
                return this._PROCESSED;
            }
            set
            {
                this.OnPROCESSEDChanging(value);
                this.ReportPropertyChanging("PROCESSED");
                this._PROCESSED = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PROCESSED");
                this.OnPROCESSEDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _PROCESSED;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPROCESSEDChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPROCESSEDChanged();
        /// <summary>
        /// There are no comments for property READY_FOR_CLIENT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool READY_FOR_CLIENT
        {
            get
            {
                return this._READY_FOR_CLIENT;
            }
            set
            {
                this.OnREADY_FOR_CLIENTChanging(value);
                this.ReportPropertyChanging("READY_FOR_CLIENT");
                this._READY_FOR_CLIENT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("READY_FOR_CLIENT");
                this.OnREADY_FOR_CLIENTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _READY_FOR_CLIENT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnREADY_FOR_CLIENTChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnREADY_FOR_CLIENTChanged();
        /// <summary>
        /// There are no comments for property BODY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string BODY
        {
            get
            {
                return this._BODY;
            }
            set
            {
                this.OnBODYChanging(value);
                this.ReportPropertyChanging("BODY");
                this._BODY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BODY");
                this.OnBODYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _BODY;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBODYChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBODYChanged();
        /// <summary>
        /// There are no comments for property TRANSFER_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<long> TRANSFER_ID
        {
            get
            {
                return this._TRANSFER_ID;
            }
            set
            {
                this.OnTRANSFER_IDChanging(value);
                this.ReportPropertyChanging("TRANSFER_ID");
                this._TRANSFER_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TRANSFER_ID");
                this.OnTRANSFER_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<long> _TRANSFER_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTRANSFER_IDChanging(global::System.Nullable<long> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTRANSFER_IDChanged();
    }
}
